### ISSUE TITLE
Specific PostegreSQL types - inet and macaddr

### ISSUE THREAD

**Issue by ethernith** [npgsql/EntityFramework6.Npgsql#114]
EF cannot mapped types inet and macaddr.
I have that fields ip and mac in table but dont have in model.

**Comment by roji** [comment]
These types are supported, but you're providing very little detail. Do you mean to say you're trying to reverse-engineer an existing database with columns of type inet and macaddr and have some sort of failure? Please post some code, the error you're seeing, etc.

**Comment by ethernith** [comment]
I create edmx model from existing database. One of database table have inet and macaddr fields. All fields mapped ok but only this two fields dont mapped.

![model](https://user-images.githubusercontent.com/15940852/45816279-68fbeb00-bcdb-11e8-9c57-5a6e3e321f06.png)

![table](https://user-images.githubusercontent.com/15940852/45816297-74e7ad00-bcdb-11e8-99a3-2d8c22d2a982.png)

**Comment by roji** [comment]
Apologies, I did not notice that you are using EF 6.x (rather than EF Core). These PostgreSQL-specific types are *not* supported in EF 6.x, which has a closed type list. EF Core fully supports these.
