### ISSUE TITLE
Unknown Transport error using push sharp

### ISSUE THREAD

**Issue by kani14** [npgsql/EntityFramework6.Npgsql#120]
I am using pushsharp library on server side to generate push notification to android and iOS devices. Everything was working fine earlier and notifications were received. But suddenly I have started receiving following error:

Unknown Transport Error at PushSharp.Android.GcmPushChannel.processResponseError(GcmAsyncParameters asyncParam) at PushSharp.Android.GcmPushChannel.responseCallback(IAsyncResult result)

Push notifications are not being received on mobile devices now. Please suggest me a solution for this.

**Comment by bgurmendi** [comment]
¿Why do you think it is related with EntityFramework6.Npgsql?

**Comment by YohDeadfall** [comment]
Closing as not related to Npgsql.
