### ISSUE TITLE
Discussion: next non-patch version to be 6.3.0

### ISSUE THREAD

**Issue by roji** [npgsql/EntityFramework6.Npgsql#123]
[With the preview release of EF 6.3.0](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-6-3-preview-with-net-core-support/), we may want our next release to align with the EF6 version number, like we do with EF Core. In other words, instead of releasing ~3.2.0~ 3.3.0 (which used to be aligned to the Npgsql ADO.NET provider, but no longer means anything), our next non-patch version would jump to 6.3.0. I think this would be much easier for our users to understand.

Opinions?

/cc @rwasef1830 @austindrenski @YohDeadfall

**Comment by austindrenski** [comment]
Sounds good to me 👍

**Comment by rwasef1830** [comment]
In my opinion, we should align the version numbers only when this EF6 provider becomes compatible with EF 6.3.0. But I also think that a branch should remain open on the old versioning scheme for bug fixes between now and 6.3.0's release for the old EF6 code.

**Comment by roji** [comment]
@rwasef1830 that was the intention - we'd release a EntityFramework6.Npgsql 3.2.1 depending on the stable EntityFramework 6.2.0, but have the dev branch build EntityFramework6.Npgsql 6.3.0 previews tracking the EF6 ones.

**Comment by YohDeadfall** [comment]
One thing I'm curious about is a feature version. How should we number the packet to reference the required version of EF6 and say that there is something new at the same time? The patch number is not an option.

**Comment by roji** [comment]
@YohDeadfall, yeah, that's a problem that we discussed also with regards to EF Core. The current system is to wait until Microsoft releases a new minor version of their own, and to include our own features at that version number.

It's not an ideal system, but there seems to be more value in tracking the upstream versions (so users know exactly what works with what). It hasn't really blocked us so far as far as I can remember.

**Comment by austindrenski** [comment]
> It hasn't really blocked us so far as far as I can remember.

I'd go even further to say that the external cadence has had a positive effect on development of EF Core provider. We get a reasonable, externally-regulated release cadence without having to decide/justify one ourselves.

**Comment by YohDeadfall** [comment]
If it would help, I'm fine with it.

**Comment by roji** [comment]
Great, thanks! I'll be releasing EF6 6.3.0-preview5 very soon (along with the super-overdue 3.2.1).
