### ISSUE TITLE
Strong Name signature could not be verified on mvc with EntityFramework6.Npgsql 3.2.1

### ISSUE THREAD

**Issue by ntuchenxy** [npgsql/EntityFramework6.Npgsql#124]
mvc project, EntityFramework6.Npgsql 3.2.1 with Npgsql 4.0.7, when start running, it reports  System.IO.FileLoadException, Could not load file or assembly "EntityFramework 6.Npgsql" or one of its dependencies, Strong Name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key,  HRESULT:0x80131045. when install EntityFramework6.Npgsql 3.2.0 with Npgsql 4.0.7, then it works well.

**Comment by roji** [comment]
Thanks for reporting, I'll publish a fix for this soon.

**Comment by roji** [comment]
Just released 3.2.1.1 which should fixed this, thanks for reporting!
