### ISSUE TITLE
Update Error，42601: syntax error at or near "("

### ISSUE THREAD

**Issue by qzwzqty** [npgsql/EntityFramework6.Npgsql#125]
hello! 

Entity Framework 6.2.0
Npgsql 4.0.7
EntityFramework6.Npgsql 3.2.1

Update SaveChanges：42601: syntax error at or near "(".
The query generated is:
UPDATE (SELECT "t_api_mapping"."id", "t_api_mapping"."api_name", "t_api_mapping"."source_name", "t_api_mapping"."condition", "t_api_mapping"."created_at", "t_api_mapping"."updated_at", "t_api_mapping"."method", "t_api_mapping"."explain", "t_api_mapping"."source_type", "t_api_mapping"."use_source" FROM "ag_datacenter"."t_api_mapping" AS "t_api_mapping") SET "updated_at"=$1 WHERE "id" = $2.

thanks!

**Comment by roji** [comment]
Can you please post the C# query and minimal model that causes this SQL to be generated?

**Comment by qzwzqty** [comment]
Code:
                using (xxDbcontext dbcontext=new xxDbcontext())
                {
                   var id = new Guid("6fb67c27-d4a1-43d8-95fb-df823a167c6e");
                    var en= dbcontext.t_api_mapping.Where(p => p.id == id).FirstOrDefault();
                    en.updated_at = DateTime.Now;
                    dbcontext.SaveChanges();
                }

**Comment by qzwzqty** [comment]
model:
public partial class t_api_mapping
    {
        public System.Guid id { get; set; }
        public string api_name { get; set; }
        public string source_name { get; set; }
        public string condition { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string method { get; set; }
        public string explain { get; set; }
        public string source_type { get; set; }
        public string use_source { get; set; }
    }

it's dbfirst

**Comment by qzwzqty** [comment]
@roji 
   在 Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.ValueTask`1.get_Result()
   在 Npgsql.NpgsqlDataReader.<NextResult>d__46.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Npgsql.NpgsqlDataReader.NextResult()
   在 Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__100.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Npgsql.NpgsqlCommand.<ExecuteNonQuery>d__92.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Npgsql.NpgsqlCommand.ExecuteNonQuery()
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   在 System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   在 System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   在 System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   在 System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   在 System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()

**Comment by qzwzqty** [comment]
> Can you please post the C# query and minimal model that causes this SQL to be generated?

hello! PostgreSQL 10

**Comment by qzwzqty** [comment]
@roji 
hello! I have tested, only this table will give an error,insert and update
![Snipaste_2019-05-30_11-18-53](https://user-images.githubusercontent.com/23160268/58606136-e2b59100-82cc-11e9-971b-009dd8b65616.png)
![Snipaste_2019-05-30_11-19-00](https://user-images.githubusercontent.com/23160268/58606139-e3e6be00-82cc-11e9-81be-8b4ae00bfda6.png)

**Comment by qzwzqty** [comment]
@roji 
I'm sorry ,reason：no primary key
