### ISSUE TITLE
PostgresException: 428C9: cannot insert into column id

### ISSUE THREAD

**Issue by ebonat** [npgsql/EntityFramework6.Npgsql#128]
1. create a simple table with pk identity:

id integer NOT NULL GENERATED BY ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
CONSTRAINT id_pkey PRIMARY KEY (id),

2. Add the EF code first and i got in the class file: I added the [Key] just in case

[DatabaseGenerated(DatabaseGeneratedOption.None)]
public int id { get; set; }

3. This C# line dbContext.SaveChanges() crashes with 

PostgresException: 428C9: cannot insert into column id

EF does not recognizes that id column is a PRIMARY KEY and IDENTITY - why?

Visual Studio .NET 2017
Npgsql 4.0.7.0
EntityFramework6.Npgsq 3.2.1.1
PostgreSQL 11.4
Windows 7

Thanks for your help!

-Ernest

**Comment by roji** [comment]
@ebonat, I don't remember exactly how EF6 works, but by DatabaseGeneratedOption.None you are asking EF6 to generate ID values and send them to the database. However, your ID definition in the database is `GENERATED ALWAYS AS IDENTITY` (without `BY` as above); that means that the column does not accept values from the application, it is *always* generated (this is exactly what PostgreSQL tells you when it says `cannot insert into column id`.

You effectively told your databases not to accept IDs from applications, and then told your application to send IDs. You can change the column definition to `GENERATED BY DEFAULT AS IDENTITY` to allow EF Core to send the IDs, or tell EF6 to not send IDs but let the database generate them (as you did above).

**Comment by ebonat** [comment]
yes, the setting GENERATED BY DEFAULT AS IDENTITY is the best solution for EF6. Still the Code First wizard missed the setting in bold below:

[**Key**]
[DatabaseGenerated(DatabaseGeneratedOption.**Identity**)]
public int id { get; set; }

**Comment by ebonat** [comment]
hi,

are we fixing this bug? it happened all the time with the id identity column using code first entity framework.

thanks roji!

**Comment by roji** [comment]
@ebonat, what exactly do you want fixed? Is the problem that your `id` property isn't automatically identified as a database-generated key? If so, can you please try to rename it to `Id` (note the upper-case I) and confirm whether that fixes the isssue?

**Comment by ebonat** [comment]
OK, let me rename the "id" column to upper-case "Id". 

So, you mean, PostgreSQL entity framework 6 is case-sensitive? Is there any difference between "id" and "Id" or "ID"?

**Comment by roji** [comment]
This has nothing to do with the PostgreSQL provider - it's about the conventions EF Core itself uses to configure keys. Take a look [at the docs](https://docs.microsoft.com/en-us/ef/core/modeling/keys#conventions):

> By convention, a property named Id or <type name>Id will be configured as the key of an entity.
