### ISSUE TITLE
How to use date_trunc in EF

### ISSUE THREAD

**Issue by tanghaojie** [npgsql/EntityFramework6.Npgsql#135]
```SQL
SELECT date_trunc('day', "CreationTime") d, count(1)
FROM table
group by d
```
result:
![image](https://user-images.githubusercontent.com/14171892/63495935-75905100-c4f3-11e9-8ab0-03f8d1b0d5ef.png)

**Comment by roji** [comment]
It should be possible to map `date_trunc` as a DbFunction and then use that in a LINQ query - search for mapping functions in EF6 (e.g. [this stackoverflow](https://stackoverflow.com/questions/27008369/calling-db-function-with-entity-framework-6)).
