### ISSUE TITLE
Unable to resolve dependencies of Npgsql and Npgsql.Entity Framework

### ISSUE THREAD

**Issue by raspberryvalley** [npgsql/EntityFramework6.Npgsql#136]
During EF migration, Update-Database step is causing problem.

I have added a new table to my existing schema by adding a model class and its dbset declaration in context class. Then i did "Add-Migration xxxx" which works fine. But "Update-Database" results in some strange npgsql version(my guess) which I had never seen before. 

The error I get in Package Manager Console is:

```cs    
System.Runtime.Serialization.SerializationException: Type is not resolved for member 'Npgsql.NpgsqlException,Npgsql, Version=2.2.4.3, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Type is not resolved for member 'Npgsql.NpgsqlException,Npgsql, Version=2.2.4.3, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
```

So I upgraded my Npgsql to a version above 3.0.1 based on the answer in [link](https://github.com/npgsql/npgsql/issues/714)

Upgrading that fails by complaining that, 

```cs    
 Unable to resolve dependencies. 'Npgsql 3.2.0' is not compatible with 'Npgsql.EntityFramework 2.2.7 constraint: Npgsql (= 2.2.7)'.
```

But my project is using Npgsql.EntityFramework 2.2.5 everywhere and not 2.2.7. 

So I tried upgrading Npgsql.EntityFramework to different versions but none of the trial-and-error version lets me upgrade Npgsql to 3.0.1 and above at all.                 

Update-Database should just work fine and update the underlying schema with newly added table. Let me know if i am doing something wrong or missing something obvious. Thanks

**Comment by roji** [comment]
Npgsql.EntityFramework is the old package for the Npgsql EF6 provider, and will most probably not work with newer versions of Npgsql. The new one is called [EntityFramework6.Npgsql](https://www.nuget.org/packages/EntityFramework6.Npgsql/3.2.1.1), depending on the latest versions of Npgsql (4.0.x).

Can you please try switching to that?

**Comment by raspberryvalley** [comment]
Thanks @roji , appreciate the quick response. I'll test and get back to you ASAP

**Comment by raspberryvalley** [comment]
Hi again,

got closer to the solution thanks to your help. Spent searching and trying various approaches, but still stuck.

Here is the summary:

EntityFramework6.npgsql has dependencies as EntityFramework (>= 6.2.0) and Npgsql (>= 4.0.7). First I made sure the EntityFramework I have is at 6.2.0. Then I went ahead to upgrade Npgsql to 4.0.9 but it still shows this error as "Unable to resolve dependencies. 'Npgsql 4.0.9' is not compatible with 'Npgsql.EntityFramework 2.2.7 constraint: Npgsql (= 2.2.7)'."

 Hence I went ahead to remove this linking between Npgsql and Npgsql.EntityFramework 2.2.7 and removed Npgsql.EntityFramework 2.2.7 before upgrading Npgsql to 4.0.7. But that resulted in more errors.

Please let me know if I am doing anything wrong. I somehow feel, I am getting stuck in cyclic dependency.

**Comment by raspberryvalley** [comment]
Thanks for the tips. I have managed to resolve the issue and appreciate the help. TY
