### ISSUE TITLE
PG12: pg_attrdef.adsrc got dropped but is still queried for

### ISSUE THREAD

**Issue by scuwe** [npgsql/EntityFramework6.Npgsql#138]
The EntityFramework data provider for .NET tries to query for the column pg_attrdef.adsrc and pg_constraint.consrc (system catalogue), which yields the following exception in Visual Studio during entity model generation:

Aufgrund der folgenden Ausnahme kann das Modell nicht generiert werden: 'System.Data.Entity.Core.EntityCommandExecutionException: Fehler beim Ausführen der Befehlsdefinition. Weitere Informationen finden Sie in der internen Ausnahme. ---> Npgsql.PostgresException: 42703: column ad.adsrc / pg_constraint.consrc does not exist

Probable reason: the table column pg_attrdef.adsrc & pg_constraint.consrc got dropped in a RC12: https://www.postgresql.org/docs/release/12.0/

**Comment by vadzvnik** [comment]
I have the same issue now

**Comment by roji** [comment]
Thanks for raising this. I'll look into this while preparing the 6.3.0 GA release, and will also look into backporting to a 3.2.2 patch release. It will take a few more days though.

**Comment by Rumpelstinsk** [comment]
Until this is resolved, is there an alternative?

Thanks

**Comment by roji** [comment]
Backported to 6.3.1 via 0f8a9df2026458e7e7036c1e5903ca1245132c3b
Backported to 3.2.2 via 209367332b230cdc3c548c6de7d04abc479cdddf

Will try to release soon to unblock this.
