### ISSUE TITLE
PG12 Can't update model from database

### ISSUE THREAD

**Issue by aster-orthrinos** [npgsql/EntityFramework6.Npgsql#143]
Hi!

Our company updated PG from 11 to 12 and now we have problems in updating our project's EF model.

This seems related to #138 

Software versions:
Database:
PostgreSQL 12.1

Developmnet environment:
Microsoft Visual Studio Community 2019
Version 16.4.2

Packages versions:
EntityFramework 6.3.0
Npgsql 4.0.10
EntityFramework6.Npgsql 3.2.1.1 
(from #138 it seems there should be v3.2.2 with fix, but Nuget did not show it, so we tried this lib with 3.2.1.1 version and then with 6.4.0)

What we tried:

First attempt:

1) RightClick on EF model opened in  VS tab
2) "Update model from database"
3) Tab "Refresh"
4) press "Finish"

got MessageBox with error: [https://ibb.co/z2SRYZd](url)
and in Output a stacktrace where general problem was
`Npgsql.PostgresException: 42703: column ad.adsrc does not exist`

Second attempt:

6) Nuget package manager -> Updated   EntityFramework6.Npgsql to version 6.4.0
7) Solution -> Clean, Rebuild -> Step 2
Got same error MessageBox and in output 
`Npgsql.PostgresException: 42703: column c.consrc does not exist`

**Comment by roji** [comment]
Seems like PG12 removed the pg_constraint.consrc column, similar to adsrc (#138). Will release a fix for this.

**Comment by roji** [comment]
I've just release 6.4.1 which should fix this.

**Comment by aster-orthrinos** [comment]
Thanks, roji! Now we can generate EF model from PG12 db using VS2019.

**Comment by gangothriurs** [comment]
> I've just release 6.4.1 which should fix this.

Hi,

I have upgraded EntityFramework6.Npgsql to 6.4.1. But it upgrades Npgsql version to 4.1.3.

But I need to downgrade Npgsql version to 4.1.1 because GAC's Npgsql version is 4.1.1.2. 
1) If I don't downgrade Npgsql version then I encounter this issue 
      https://github.com/npgsql/npgsql/issues/445#issue-53056116
2) If I downgrade Npgsql to 4.1.1 then EntityFramework6.Npgsql downgrades to 6.3.0. This will 
      result in  "Npgsql.PostgresException: 42703: column ad.adsrc does not exist".

The latest version of Npgsql PostgreSQL Integration available in VS marketplace is 4.1.1.2.
https://marketplace.visualstudio.com/items?itemName=RojanskyS.NpgsqlPostgreSQLIntegration

**Comment by roji** [comment]
I've just uploaded version 4.1.3.1 of the VSIX to the VS marketplace. Please install it and make sure you take a dependency on that nuget version in your project.

**Comment by gangothriurs** [comment]
> I've just uploaded version 4.1.3.1 of the VSIX to the VS marketplace. Please install it and make sure you take a dependency on that nuget version in your project.

Thanks it's working now.

**Comment by roji** [comment]
@gangothriurs thanks for confirming!
