### ISSUE TITLE
Conexão através do Excel com o Postgresql usando o Npgsql

### ISSUE THREAD

**Issue by jhonmelo2020** [npgsql/EntityFramework6.Npgsql#152]
Olá!!! Preciso de ajuda!!!!!!!!!!
Atualmente trabalho com conexões no banco de dados, usando o Excel com o Npgsql v4.0.10, funciona corretamente. Porém se eu tentar instalar qualquer versão superior, o Excel já não consegue se conectar por completo, e retorna o seguinte erro:

DataSource.Error: Ocorreu um erro ao ler dados do provedor:
'Não foi possível carregar arquivo ou assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, 
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.'
Detalhes:
DataSourceKind=PostgreSQL

Alguém sabe como resolver?

**Comment by roji** [comment]
Duplicate of #2677. Please try the experimental MSI posted on that issue and post back on whether it helped!

**Comment by adrianodss** [comment]
Good people!

Would you have any tips on connecting npgsql with aws rds using cert .PEM?
