### ISSUE TITLE
Missing tag for v6.4.1

### ISSUE THREAD

**Issue by Bouke** [npgsql/EntityFramework6.Npgsql#153]
The package released under version 6.4.1 is not tagged, and as such not discoverable on GitHub. Can you tag the correct commit / create release on GitHub, ideally also including release notes? Thank you.

**Comment by roji** [comment]
Thanks, have pushed the tag and created a [github release](https://github.com/npgsql/EntityFramework6.Npgsql/releases/tag/v6.4.1) linking to the milestone with the issues.
