### ISSUE TITLE
Problem with Bulk operation under net472

### ISSUE THREAD

**Issue by Prutenskiy** [npgsql/EntityFramework6.Npgsql#169]
I have app witch configured as <TargetFrameworks>net472;netcoreapp3.1</TargetFrameworks>
I use Npgsql 4.*(try any vertions) for work with DB
INSERT\UPDATE worked fine, but when I try use bulk operation then on start app under net472 have this exception
"Void Npgsql.Bulk.NpgsqlBulkUploader..ctor(Microsoft.EntityFrameworkCore.DbContext)".

For bulk operation I try like this:
            using (var ctx = new MyContext(NpgsqlDbContextOptionsExtensions.UseNpgsql(new DbContextOptionsBuilder(), _connectionStr).Options))
            {
                var d = new List<UserByRole>();

                var uploader = new NpgsqlBulkUploader(ctx);
                uploader.Insert(d, Npgsql.Bulk.InsertConflictAction.Update<UserByRole>(........));
            }

Have any some advise?

**Comment by Emill** [comment]
Hi. Could you please post the full stack trace and exception.

Also maybe https://github.com/neisbut/Npgsql.Bulk would be a better place to file this issue.

**Comment by Prutenskiy** [comment]
Call stack:
   at PGTestCommand.Test.Run() in C:\...\Program.cs:line 45
   at PGTestCommand.Program.Main(String[] args) in C:\...\Program.cs:line 13

Exception Message:
Method not finde: "Void Npgsql.Bulk.NpgsqlBulkUploader..ctor(Microsoft.EntityFrameworkCore.DbContext)".

You meen move issue in other repo?

**Comment by Prutenskiy** [comment]
transfer to other repo https://github.com/neisbut/Npgsql.Bulk/issues/62
