### ISSUE TITLE
npgsql can't define parameter's subquerie type (42883)

### ISSUE THREAD

**Issue by tomori-bestWaifu** [npgsql/EntityFramework6.Npgsql#171]
Npgsql 5.0.5
VS 2019, C# winforms app

I have following NpgsqlCommand: 
```
string sql_in_count = "(SELECT count(*) FROM mydb_schema.documents WHERE documents.lead_by = employees.empl_id AND documents.in_doc IS TRUE)";
string sql_out_count = "(SELECT count(*) FROM mydb_schema.documents WHERE documents.lead_by = employees.empl_id AND documents.in_doc IS FALSE)";

string sql_str = "SELECT empl_id, FIO, " + sql_in_count + " AS in_count, " + sql_out_count + " AS out_count, " + "award, total_salary " +
                "FROM mydb_schema.employees JOIN mydb_schema.salary ON empl_num = empl_id WHERE boss = mydb_schema.id_by_username(session_user::text) " +
                "GROUP BY(empl_id, FIO, award, total_salary) " +
                "HAVING(:having_rule  > :min_doc_amount)";
```

My two parametrs are "having_rule" and "min_doc_amount" which I compare. 
```
var having_rule = display_table.CreateParameter(); having_rule.ParameterName = ("having_rule"); 
having_rule.NpgsqlDbType = NpgsqlDbType.Text;
having_rule.Value = sql_in_count;
display_table.Parameters.Add(having_rule);

var min_doc_amount = display_table.CreateParameter(); min_doc_amount.ParameterName = ("min_doc_amount");
min_doc_amount.NpgsqlDbType = NpgsqlDbType.Integer;
min_doc_amount.Value = (int)min_doc_amount_comboBox.Text[0]; // make func for 2+ digs
display_table.Parameters.Add(min_doc_amount);
```
The issue is npgsql doesn't know that result of having_rule's subquerie is Integer, so:

- If I set NpgsqlDbType of "having_rule" as Text and "min_doc_amount" as Integer I get "42883: operator doesn't exist : text > integer"
- If I set NpgsqlDbType of "having_rule" as Integer and "min_doc_amount" as Integer I can't set a subquerie as my having_rule.Value
- If I set NpgsqlDbType of "having_rule" as Text and "min_doc_amount" as Text I get an empty table:
![image](https://user-images.githubusercontent.com/85434339/120919504-a5a5e580-c6c2-11eb-8f13-c2699ed47f6c.png)

This is how it should be (if I collect my sql_str with adding strings):
```
string sql_str = "SELECT empl_id, FIO, " + sql_in_count + " AS in_count, " + sql_out_count + " AS out_count, " + "award, total_salary " +
                "FROM mydb_schema.employees JOIN mydb_schema.salary ON empl_num = empl_id WHERE boss = mydb_schema.id_by_username(session_user::text) " +
                "GROUP BY(empl_id, FIO, award, total_salary) " +
                "HAVING " + sql_in_count + " > " + min_doc_amount_comboBox.Text;
```
![image](https://user-images.githubusercontent.com/85434339/120919542-dbe36500-c6c2-11eb-8132-d078d479389d.png)

I also cant execute having_rule's subquerie and pass to paramenter int result, because subquerie  references other table in parent querie.
What would you recommend me do?

**Comment by Emill** [comment]
You can't have an sql statement as a parameter. Parameters contain plain values, not sql queries.

Replace ":having_rule" with "in_count" and you should be good to go.

**Comment by tomori-bestWaifu** [comment]
Ok, thx!
