### ISSUE TITLE
EF6 together with EFCore6

### ISSUE THREAD

**Issue by viniciusverasdossantos** [npgsql/EntityFramework6.Npgsql#177]
I need to run EF6 together with EFCore6. Is the npgsql 6 package compatible with EntityFramework6.Npgsql? I'm afraid there might be some kind of problem

**Comment by roji** [comment]
@viniciusverasdossantos not really. You may try to use Npgsql 6 with EntityFramework6.Npgsql, but this combination was never tested and may have issues.

EntityFramework6.Npgsql is pretty much archived at this point - there's no more work happening on it.
