### ISSUE TITLE
Relation to https://github.com/npgsql/efcore.pg ?

### ISSUE THREAD

**Issue by mausch** [npgsql/EntityFramework6.Npgsql#187]
I was just looking for the repo for the EF+npgsql integration to figure out some issue.
Found this one and https://github.com/npgsql/efcore.pg

This one has no README and judging by the commit dates it seems to be deprecated?
Would be good to have a README here to clarify.

Thanks!

EDIT ah I just realised this is for the pre-.netcore EF? It's kinda confusing now that there's EFCore 6.x

**Comment by roji** [comment]
Yeah:

* https://github.com/npgsql/efcore.pg is the Npgsql EF Core provider for PostgreSQL. It's very actively maintained (and has a README)
* https://github.com/npgsql/EntityFramework6.Npgsql is the old Npgsql non-core EF provider. Like non-core EF6 itself, it's no longer being actively maintained. I'll add a README here to make that clearer.
