### ISSUE TITLE
NpgsqlTypes.NpgsqlTimeSpan not found

### ISSUE THREAD

**Issue by filipeve** [npgsql/EntityFramework6.Npgsql#189]
Could not load type 'NpgsqlTypes.NpgsqlTimeSpan' from assembly 'Npgsql, Version=7.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'

Npgsql 7.0 Release Notes
The obsoleted NpgsqlDateTime, NpgsqlDate and NpgsqlTimeSpan have been removed

**Comment by roji** [comment]
It's recommended to not upgrade the Npgsql version when using the old EF 6 provider. As long as you're using EF 6, stay on the same Npgsql version which works.
