### ISSUE TITLE
Are you planning to update the repo?

### ISSUE THREAD

**Issue by AmSoMad** [npgsql/EntityFramework6.Npgsql#190]
Entity Framework 7 has been released.
Are you planning to update the repo?

i read https://learn.microsoft.com/ko-kr/dotnet/api/overview/azure/postgresql?view=azure-dotnet

but.
It's under technical review, and you need to check if the repo has been updated.

**Comment by roji** [comment]
You're in the wrong repo - this is the old, non-core EF. The EF Core provider is developer in https://github.com/dotnet/efcore.
