### ISSUE TITLE
Issues on Npgsql 7

### ISSUE THREAD

**Issue by ayauka** [npgsql/EntityFramework6.Npgsql#191]
There are several issues on migrations, this exception is thrown:
Could not load type 'NpgsqlTypes.NpgsqlTimeSpan' from assembly 'Npgsql, Version=7.0.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'

Is related with deprecated types on Npgsql 7.

https://github.com/npgsql/EntityFramework6.Npgsql/blob/4b54a479d6975b9b39c79dc310664e735a1719b4/EF6.PG/NpgsqlMigrationSqlGenerator.cs#L756

**Comment by roji** [comment]
@ayauka since there's no longer any active development of the non-core EF 6 proviner, it isn't compatible with new versions of Npgsql. It's recommended to stay on the Npgsql version referenced by the provider, and not attempt to newer major versions.
