### ISSUE TITLE
Can u give me vsix version 4.1.3.1 ?

### ISSUE THREAD

**Issue by DentaDiz** [npgsql/EntityFramework6.Npgsql#198]
I've just uploaded version 4.1.3.1 of the VSIX to the VS marketplace. Please install it and make sure you take a dependency on that nuget version in your project.

_Originally posted by @roji in https://github.com/npgsql/EntityFramework6.Npgsql/issues/143#issuecomment-594067504_

**Comment by roji** [comment]
@DentaDiz the VSIX versions are available on the [VS marketplace](https://marketplace.visualstudio.com/items?itemName=RojanskyS.NpgsqlPostgreSQLIntegration); other than that, both VSIX and Entity Framework 6 (non-core) are no longer being maintained.

**Comment by DentaDiz** [comment]
VS marketplace only latest version vsix 4.1.12.
i have a problem Npgsql.PostgresException: 42703: column ad.adsrc does not exist.

EntityFramework : 6.0.0.0
EntityFramework.SqlServer : 6.0.0.0
EntityFramework6.Npgsql : 3.2.1.1
Npgsql : 4.1.2.0
Npgsql vsix : 4.1.1.2
.net Framework : 4.8.1

**Comment by roji** [comment]
4.1.12 is newer than 4.1.3.1, and contains all the fixes in the latter.

In any case, the problem with `ad.adsrc` which you're encountering is #138, which was fixed in EntityFramework6.Npgsql 6.4.0 - make sure you're on the latest version of that package. This has nothing to do with the VSIX.
