### ISSUE TITLE
clarification about bugfix support

### ISSUE THREAD

**Issue by mrmandrake** [npgsql/EntityFramework6.Npgsql#202]
We have a product based on latest nuget package EF6.NpgSQL (v6.4.2); we need to know if a vulnerability detection (CVE) in this library is considered "critical bug" (as written in README) and trigger active maintenance to solve it.

**Comment by NinoFloris** [comment]
Active work on EF6.NpgSQL itself ceased some years ago, and we're unlikely to release any new versions. To fix the [Npgsql vulnerability](https://github.com/advisories/GHSA-x9vc-6hfv-hg8c) I'm assuming you're referring to you should directly include the latest version of Npgsql 4.1.x (which is what EF6.NpgSQL 6.4.2 depends on) in your own project instead.

Currently that would be Npgsql 4.1.14, see https://www.nuget.org/packages/Npgsql/4.1.14.

**Comment by mrmandrake** [comment]
Thank you Nino for this fast reply, I try to explain me better:  at now we are using ef6.npgsql 6.4.2 with npgsql 6.0.11 ; i posed previous question because for FDA standard compliance we have to be sure any newer vulnerability found in EntityFramework6.Npgsql will be fixed by your team.

**Comment by Emill** [comment]
I think there are bigger risks that there would be any vulnerabilities in core Npgsql than this repo, since this is just a simple plugin for EF6. In any case, I don't see why we would not fix any security issues found in this repo only because it's quite old.

**Comment by NinoFloris** [comment]
Though @roji might have a more targeted answer, you should assume updates to EF6.Npgsql will be unlikely for anything but the most critical issues. Regarding Npgsql, that is another matter, there we are unlikely to make further updates to the 4.x and 5.x branches going forward (so not directly relevant to your case). 

Keep in mind we're not a commercial entity. These long term support efforts mostly depend on the work required, the reported usage of the relevant version(s) by users and nuget, and sometimes just whether somebody can make a persuasive argument as to why it should really be updated (e.g. 4.x was released in 2018).

**Comment by roji** [comment]
Pretty much agree with everything said above... For both EntityFramework6.Npgsql and older versions of Npgsql (where older current means before 6.0, but will soon change to before 8.0), we most likely won't be fixing anything that isn't a critical/security bug. For critical/security bugs, we'll do what we can on a best-effort basis (and the track record has generally been pretty good here), but there are no formal guarantees/commitments as this is a community-maintained project.
