### ISSUE TITLE
Postgre can't detect type from const strings (add ::text)

### ISSUE THREAD

**Issue by roji** [npgsql/EntityFramework6.Npgsql#27]
_From @smstuebe on October 27, 2015 9:55_

When the Queries get complex, we often see `'0X0X'` in the SELECT statements.
Unfortunately Postgre fails to detect the type of constants if the SELECTS are inner SELECTS. A simple description of this Problem: 
http://stackoverflow.com/questions/18073901/failed-to-find-conversion-function-from-unknown-to-text 

Query from query log:
```sql
SELECT   "Project2"."id", 
         "Project2"."C2" AS "C1", 
         "Project2"."C1" AS "C2", 
         "Project2"."description", 
         "Project2"."creation_date", 
         "Project2"."vehicle_brand_id", 
         "Project2"."country_variant_id", 
         "Project2"."hardware_variant_id", 
         "Project2"."type_id", 
         "Project2"."sop_date_id", 
         "Project2"."project_id", 
         "Project2"."release_date_id", 
         "Project2"."config", 
         "Project2"."released", 
         "Project2"."number_index", 
         "Project2"."deprecated", 
         "Project2"."field", 
         "Project2"."blocked", 
         "Project2"."link_teamforge", 
         "Project2"."link_infopool", 
         "Project2"."release_info", 
         "Project2"."release_info_short", 
         "Project2"."train_status", 
         "Project2"."created", 
         "Project2"."creator", 
         "Project2"."last_modified", 
         "Project2"."last_modifier", 
         "Project2"."name", 
         "Project2"."C3", 
         "Project2"."C5" AS "C4", 
         "Project2"."id1", 
         "Project2"."C4" AS "C5", 
         "Project2"."description1", 
         "Project2"."device_number_type", 
         "Project2"."kpmwebprnumber", 
         "Project2"."vehicle_brand_id1", 
         "Project2"."parent_id", 
         "Project2"."platform_id", 
         "Project2"."doors_name", 
         "Project2"."created1", 
         "Project2"."creator1", 
         "Project2"."last_modified1", 
         "Project2"."last_modifier1", 
         "Project2"."name1" 
FROM     ( 
                         SELECT          "Alias1"."id", 
                                         "Alias1"."description", 
                                         "Alias1"."creation_date", 
                                         "Alias1"."vehicle_brand_id", 
                                         "Alias1"."country_variant_id", 
                                         "Alias1"."hardware_variant_id", 
                                         "Alias1"."type_id", 
                                         "Alias1"."sop_date_id", 
                                         "Alias1"."project_id", 
                                         "Alias1"."release_date_id", 
                                         "Alias1"."config", 
                                         "Alias1"."released", 
                                         "Alias1"."number_index", 
                                         "Alias1"."deprecated", 
                                         "Alias1"."field", 
                                         "Alias1"."blocked", 
                                         "Alias1"."link_teamforge", 
                                         "Alias1"."link_infopool", 
                                         "Alias1"."release_info", 
                                         "Alias1"."release_info_short", 
                                         "Alias1"."train_status", 
                                         "Alias1"."created", 
                                         "Alias1"."creator", 
                                         "Alias1"."last_modified", 
                                         "Alias1"."last_modifier", 
                                         "Alias1"."name", 
                                         "Alias1"."C1", 
                                         "Alias1"."C2", 
                                         "Alias1"."C3", 
                                         "Extent3"."id"          AS "id1", 
                                         "Extent3"."description" AS "description1", 
                                         "Extent3"."device_number_type", 
                                         "Extent3"."kpmwebprnumber", 
                                         "Extent3"."vehicle_brand_id" AS "vehicle_brand_id1",
                                         "Extent3"."parent_id", 
                                         "Extent3"."platform_id", 
                                         "Extent3"."doors_name", 
                                         "Extent3"."created"       AS "created1", 
                                         "Extent3"."creator"       AS "creator1", 
                                         "Extent3"."last_modified" AS "last_modified1", 
                                         "Extent3"."last_modifier" AS "last_modifier1", 
                                         "Extent3"."name"          AS "name1", 
                                         CASE 
                                                         WHEN ( 
                                                                                         "Extent2"."vehicle_id" IS NULL) THEN (Cast (NULL AS TEXT))
                                                         ELSE (e'bc1f6d3a-e7c0-4e64-a4a6-9238b7fb45bc') 
                                         END AS "C4", 
                                         CASE 
                                                         WHEN ( 
                                                                                         "Extent2"."vehicle_id" IS NULL) THEN (cast (NULL AS int4))
                                                         ELSE (1) 
                                         END AS "C5" 
                         FROM            ( 
                                                  SELECT   "Project1"."C1", 
                                                           "Project1"."id", 
                                                           "Project1"."description", 
                                                           "Project1"."creation_date", 
                                                           "Project1"."vehicle_brand_id", 
                                                           "Project1"."country_variant_id", 
                                                           "Project1"."hardware_variant_id", 
                                                           "Project1"."type_id", 
                                                           "Project1"."sop_date_id", 
                                                           "Project1"."project_id", 
                                                           "Project1"."release_date_id", 
                                                           "Project1"."config", 
                                                           "Project1"."released", 
                                                           "Project1"."number_index", 
                                                           "Project1"."deprecated", 
                                                           "Project1"."field", 
                                                           "Project1"."blocked", 
                                                           "Project1"."link_teamforge", 
                                                           "Project1"."link_infopool", 
                                                           "Project1"."release_info", 
                                                           "Project1"."release_info_short", 
                                                           "Project1"."train_status", 
                                                           "Project1"."created", 
                                                           "Project1"."creator", 
                                                           "Project1"."last_modified", 
                                                           "Project1"."last_modifier", 
                                                           "Project1"."name", 
                                                           "Project1"."C2", 
                                                           "Project1"."C3" 
                                                  FROM     ( 
                                                                  SELECT "Extent1"."id", 
                                                                         "Extent1"."description",
                                                                         "Extent1"."creation_date",
                                                                         "Extent1"."vehicle_brand_id",
                                                                         "Extent1"."country_variant_id",
                                                                         "Extent1"."hardware_variant_id",
                                                                         "Extent1"."type_id",
                                                                         "Extent1"."sop_date_id",
                                                                         "Extent1"."project_id",
                                                                         "Extent1"."release_date_id",
                                                                         "Extent1"."config", 
                                                                         "Extent1"."released",
                                                                         "Extent1"."number_index",
                                                                         "Extent1"."deprecated",
                                                                         "Extent1"."field", 
                                                                         "Extent1"."blocked",
                                                                         "Extent1"."link_teamforge",
                                                                         "Extent1"."link_infopool",
                                                                         "Extent1"."release_info",
                                                                         "Extent1"."release_info_short",
                                                                         "Extent1"."train_status",
                                                                         "Extent1"."created",
                                                                         "Extent1"."creator",
                                                                         "Extent1"."last_modified",
                                                                         "Extent1"."last_modifier",
                                                                         "Extent1"."name", 
                                                                         e'0X0X'                           AS "C1",
                                                                         e'bc1f6d3a-e7c0-4e64-a4a6-9238b7fb45bc' AS "C2", 
                                                                         e'Vehicles'                             AS "C3"
                                                                  FROM   "public"."train"                        AS "Extent1"
                                                                  WHERE  "Extent1"."Discriminator" = e'Train'
                                                                  AND    "Extent1"."config" != true) AS "Project1"
                                                  ORDER BY "Project1"."id" ASC limit 10) AS "Alias1"
                         LEFT OUTER JOIN "public"."vehicle_x_train"                      AS "Extent2"
                         INNER JOIN      "public"."vehicle"                              AS "Extent3"
                         ON              "Extent3"."id" = "Extent2"."vehicle_id" 
                         ON 
                                         CASE 
                                                         WHEN ( 
                                                                                         "Alias1"."C1" LIKE e'0X%') THEN ("Alias1"."id")
                                         END = "Extent2"."train_id") AS "Project2" 
ORDER BY "Project2"."id" ASC , 
         "Project2"."C5" ASC
```

When I specifiy the type implicitly with changing the line
```sql 
e'0X0X' AS "C1",
```
to
```sql
e'0X0X'::text AS "C1",
```
the query is executed without any Problems.

Could you implement explicit typing for this constants? Or is there already any solution for this? Where does this Hugs and Kisses '0X0X' come from? Is this a EF or a npgsql 'feature'?

Our Environment:
Postgre 9.4
npgSQL 3.0.3
EntityFramework6.Npgsql 3.0.3
EntityFramework 6.1.3

_Copied from original issue: npgsql/npgsql#837_

**Comment by roji** [comment]
The 0X0X definitely comes from EF and not from Npgsql. I guess on way to fix this would be to generate ::TEXT on all string literals, although there may be a better way. I'll try to dig deeper.

**Comment by roji** [comment]
_From @smstuebe on October 27, 2015 18:21_

yep. I'll try to change it it on a fork. I had a look at the code after I submitted the issue. It should be a oneliner. 
EDIT: Ohh VS 2015.

**Comment by roji** [comment]
Yeah, sorry about that...

You should probably work on the branch hotfix/3.0.4 rather than develop, which is in a complicated state at the moment because of DNX/project.json.

I'll wait for your fix, it would be good to include this in 3.0.4.

**Comment by roji** [comment]
_From @smstuebe on October 30, 2015 15:1_

Hi I have send a pull request. It fixes the problem in our environment. Unfortunately, I couldn't execute the unit tests. Could you please double check it?

**Comment by roji** [comment]
_From @Emill on October 30, 2015 19:14_

We actually removed ::text to be able to support other datatypes represented as strings. It's a bit more complicated to get this working.
I'll try to figure out if anything can be done.

**Comment by roji** [comment]
_From @smstuebe on October 30, 2015 22:37_

Ahh ok. I was wondering, why string is the only datatype that isn't explicitly typed. What other types do you mean?

**Comment by roji** [comment]
@smstuebe, the idea was to allow string values to be sent for colulmn types such as xml, jsonb. If you type the values by adding ::text, PostgreSQL rejects them because it refuses to implicitly cast text to json. If you leave out the ::text, PostgreSQL treats it as "unknown" and is OK with implicitly casting.

@Emill, thanks for looking at this...

**Comment by roji** [comment]
_From @smstuebe on October 31, 2015 14:53_

Ok. Just out of curiosity, does npgsql support json queries (e.g. http://schinckel.net/2014/05/25/querying-json-in-postgres/)?

**Comment by roji** [comment]
@smstuebe, Npgsql doesn't really have anything to do with JSON queries or anything else that happens in the SQL you send to PostgreSQL; Npgsql's job is simply to send the query to PostgreSQL (with any parameters) and parse the results. So yes, JSON queries and any other PostgreSQL SQL feature is "supported" by Npgsql.

**Comment by roji** [comment]
@Emill, any idea about this? I hope to release 3.0.4 soon.

**Comment by roji** [comment]
_From @setifo on December 2, 2015 20:36_

hi guys, what's up with this topic? it's a bit annoying to have that kind of statements where npgsql couldn't help out :(
entitiy framework is creating this 0X0X-thing for us too, and postgres isn't able to select the right type :(

**Comment by roji** [comment]
_From @Emill on December 2, 2015 23:14_

Sorry for not catching up on this...
Do you have example C# Linq code that reproduces this issue?

2015-12-02 21:36 GMT+01:00 setifo <notifications@github.com>:

**Comment by roji** [comment]
_From @setifo on December 3, 2015 20:22_

In our case we want to eager load a more or less complex datamodel.
I've changed the names of the Entities.

UseCase is loading all Entities of A as queryable and eager load additional data. The whole data set is going to be exported into an XML file.

Datamodel is something like:
A references B and C
B references C
C references D and X
X has properties we want to include (LeftFile, RightFile)

result = Queryable()
                    .Include(t => t.C.Select(e => e.D))
                    .Include(t => t.C.Select(e => e.X.Select(dn => dn.LeftFile)))
                    .Include(t => t.C.Select(e => e.X.Select(dn => dn.RightFile)))
                    .Include(t => t.B.Select(tr => tr.C.Select(e => e.D)))
                    .Include(t => t.B.Select(tr => tr.C.Select(e => e.X.Select(dn => dn.LeftFile))))
                    .Include(t => t.B.Select(tr => tr.C.Select(e => e.X.Select(dn => dn.RightFile))));

=> Entity Framework creates an inner select with the 0X0X thing. If we add the magic ::text the sql query works.

If I simplify the linq or divide it into two, it works like a charme, too. (no inner select, no 0X0X)
e.g.:
result = Queryable()
                    .Include(t => t.C.Select(e => e.D))
                    .Include(t => t.C.Select(e => e.X.Select(dn => dn.LeftFile)))
                    .Include(t => t.C.Select(e => e.X.Select(dn => dn.RightFile)));

result = Queryable()
                    .Include(t => t.B.Select(tr => tr.C.Select(e => e.D)))
                    .Include(t => t.B.Select(tr => tr.C.Select(e => e.X.Select(dn => dn.LeftFile))))
                    .Include(t => t.B.Select(tr => tr.C.Select(e => e.X.Select(dn => dn.RightFile))));

**Comment by roji** [comment]
_From @Emill on December 6, 2015 23:2_

Can you give a more detailed example?
I couldn't reproduce the issue with the following code. No 0X0X strings are shown up in the SQL query.

Models:

        public class Issue837A
        {
            public string Issue837AId { get; set; }

            public virtual List<Issue837B> Issue837Bs { get; set; }
            public virtual List<Issue837C> Issue837Cs { get; set; }
        }

        public class Issue837B
        {
            public string Issue837BId { get; set; }

            public virtual Issue837A Issue837A { get; set; }

            public virtual List<Issue837C> Issue837Cs { get; set; }
        }

        public class Issue837C
        {
            public string Issue837CId { get; set; }

            public virtual Issue837D Issue837D { get; set; }
            public virtual Issue837A Issue837A { get; set; }
            public virtual Issue837B Issue837B { get; set; }

            public virtual List<Issue837X> Issue837Xs { get; set; }
        }

        public class Issue837D
        {
            public string Issue837DId { get; set; }

            public virtual List<Issue837C> Issue837Cs { get; set; }
        }

        public class Issue837X
        {
            public string Issue837XId { get; set; }
            public Issue837Prop1 Issue837Prop1 { get; set; }
            public Issue837Prop2 Issue837Prop2 { get; set; }

            public virtual Issue837C Issue837C { get; set; }
        }

        public class Issue837Prop1
        {
            public string Issue837Prop1Id { get; set; }
        }

        public class Issue837Prop2
        {
            public string Issue837Prop2Id { get; set; }
        }


Query:

        var result = context.Issue837As
        .Include(t => t.Issue837Cs.Select(e => e.Issue837D))
        .Include(t => t.Issue837Cs.Select(e => e.Issue837Xs.Select(dn => dn.Issue837Prop1)))
        .Include(t => t.Issue837Cs.Select(e => e.Issue837Xs.Select(dn => dn.Issue837Prop2)))
        .Include(t => t.Issue837Bs.Select(tr => tr.Issue837Cs.Select(e => e.Issue837D)))
        .Include(t => t.Issue837Bs.Select(tr => tr.Issue837Cs.Select(e => e.Issue837Xs.Select(dn => dn.Issue837Prop1))))
        .Include(t => t.Issue837Bs.Select(tr => tr.Issue837Cs.Select(e => e.Issue837Xs.Select(dn => dn.Issue837Prop2))));
        result.ToArray();

**Comment by roji** [comment]
_From @rwasef1830 on April 25, 2016 23:32_

@Emill  @roji 

Couldn't a better solution just be to send strings as strings and then just implement a generic Cast SQL function for entity framework that takes the target postgresql type as a string ?

For ```INSERT``` or ```UPDATE```, the current behavior makes sense, but for ```SELECT``` the user writing the query can write explicit casts, and for entity framework, we can implement an entity framework ```SqlCast``` function that takes the string value and the postgresql type name as a string, and do some special case handling in SqlGenerator to handle quoting properly for that parameter.

Unfortunately, it would be a breaking change. But the current behavior is already broken because especially when using table-per-subclass inheritance pattern and doing polymorphic query, EF generates the 0X0X0X strings as a kind of type discriminator for child classes and when the query gets complex, and EF does an inner ```SELECT```, the ```XX000: failed to find conversion function from unknown to text``` error is returned.

I imagine it could be used like this:
```csharp

var ewkbHex = "0101000020E6100000CDCCCCCCCC8C4040CDCCCCCCCC8C4040"; // POINT(33.1 33.1) SRID=4326
dbContext.Stores.Where(x => x.Coordinates == NpgsqlFunctions.SqlCast(ewkbHex, "geography"));

public static class NpgsqlFunctions
{
    public static string SqlCast(string unknownTypeValue, string postgreSqlTypeName)
    {
        throw new NotSupportedException();
    }
}
```
Should emit the equivalent of:
```sql
SELECT * FROM "Stores" WHERE "Coordinates" = CAST(E'0101000020E6100000CDCCCCCCCC8C4040CDCCCCCCCC8C4040' AS geography);
```

**Comment by roji** [comment]
_From @rwasef1830 on April 26, 2016 1:24_

See #1045 for an implementation idea / example.

Note that the test ```EntityFrameworkBasicTests.InsertAndSelect``` needed to be updated to pass after my changes. 

This constitutes a breaking change in behavior. Requesting comments / feedback.

**Comment by roji** [comment]
_From @Emill on April 26, 2016 8:34_

I guess this seems a pretty good way of doing it, although a bit hacky. I
don't know what the guys that created EF6 thought about restricting the
data types. EF7 seems way better.


2016-04-26 3:24 GMT+02:00 Raif Atef <notifications@github.com>:

**Comment by rwasef1830** [comment]
@roji @Emill 
I've managed to get a working test case that reproduces this issue:
https://github.com/rwasef1830/EntityFramework6.Npgsql/commit/871a8fa257000b2ae8fcb5ff6fe61256a583bffa

To make the unit test pass, a one line fix needs to be made:
```patch
 src/EntityFramework6.Npgsql/SqlGenerators/VisitedExpression.cs | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/EntityFramework6.Npgsql/SqlGenerators/VisitedExpression.cs b/src/EntityFramework6.Npgsql/SqlGenerators/VisitedExpression.cs
index 0f468d0..a524881 100644
--- a/src/EntityFramework6.Npgsql/SqlGenerators/VisitedExpression.cs
+++ b/src/EntityFramework6.Npgsql/SqlGenerators/VisitedExpression.cs
@@ -242,7 +242,7 @@ internal override void WriteSql(StringBuilder sqlText)
                     sqlText.Append("::uuid");
                     break;
                 case PrimitiveTypeKind.String:
-                    sqlText.Append("E'").Append(((string)_value).Replace(@"\", @"\\").Replace("'", @"\'")).Append("'");
+                    sqlText.Append("E'").Append(((string)_value).Replace(@"\", @"\\").Replace("'", @"\'")).Append("'::varchar");
                     break;
                 case PrimitiveTypeKind.Time:
                     sqlText.AppendFormat(ni, "INTERVAL '{0}'", (NpgsqlTimeSpan)(TimeSpan)_value);

```

Unfortunately, this causes all queries that pass strings for "unknown" types need to use an explicit cast function (I implemented one in https://github.com/rwasef1830/EntityFramework6.Npgsql/commit/2e2f03fe0042a5697e25ec0eea632112a5b32196). This is a breaking change.

I can't figure out any other way to solve this without breaking changes because there is no way to catch the EF-generated identifier (```0X0X0X``` pattern) reliably from user-passed constant values. Perhaps we can default to the current behavior and add a new connection string parameter to not treat string as unknown ?

If that's ok I can implement it and make a complete pull request with all changes. Otherwise, I'm open to suggestions.

This is similar to my earlier pull request (https://github.com/npgsql/npgsql/pull/1045), except I removed the special handling of SELECT statements and added a unit test, so it is a cleaner implementation, but still breaks compatibility with people who pass "strings" for unknown types.

**Comment by rwasef1830** [comment]
Redid the test case because because I had removed a ```Where``` which caused EF to generate a ```UNION``` query which didn't reproduce the issue.

**Comment by rwasef1830** [comment]
Found a simpler approach that doesn't break any of the old unit tests. Instead of forcing all strings to have ``::varchar``, just intercept projection expressions and if one of the projection list is a ```DbConstantExpression```, wrap it in a cast to varchar.

This introduces a smaller breaking change, and that is in the scenario where a user does an operation on a selected constant string expression that is supposed to represent an "unsupported" type, but this scenario should be very rare, so this fix is pretty safe. The workaround is just to use the explicit cast function.

**Comment by roji** [comment]
@rwasef1830, I finally sat down to work on this. I'm not sure I fully understand everything so feel free to correct me, it seems you have a better understanding. @Emill, if you have any spare time your advice would be appreciated.

The way I understand it, we have 2 different issues here: The 0X0X bug (#27), and support for PG types which aren't natively supported by EF6, via strings.

To support unsupported types as strings, work was done by @Emill in https://github.com/npgsql/npgsql/issues/600: string parameters are sent with `NpgsqlDbType.Unknown` to allow PostgreSQL to implicitly cast them, and `UnknownResultTypeList` is set for all (CLR) string properties being read to get strings. This should be sufficient to support unsupport types as strings.

The 0X0X bug (#27) seems to be caused by rendering of SQL string *literals*. The `ConstantExpression` class, responsible for rendering all literals, renders strongly-typed SQL (appending ::uid etc.) except for strings, apparently again, to allow string literals to be sent for other columns. This is what causes #27.

But this is the part I don't understand: EF6 shouldn't be writing any *user* data as literals, should it? These should always go through as parameters. SqlBaseGenerator has a `CreateParametersForConstants` flag, which seems to be false for select statements (see and for migrations (see `NpgsqlServices.TranslateCommandTree`). I don't see the reasoning behind rendering constants as literals in select statements - maybe someone can enlighten me (we don't really care about migrations in this context).

So IMHO, unless I'm really misunderstanding the whole thing, if we make the provider use parameters for all statement types, we can simply add `::varchar` to string literal handling in `ConstantExpression` solving the 0X0X bug and maintaining support for unsupported types as string.

Waiting for your comments...

**Comment by rwasef1830** [comment]
@roji This is a bit convoluted to explain, I'll do my best :-)

**Comment by rwasef1830** [comment]
@roji 

>But this is the part I don't understand: EF6 shouldn't be writing any user data as literals, should it? These should always go through as parameters. SqlBaseGenerator has a CreateParametersForConstants flag, which seems to be false for select statements (see and for migrations (see NpgsqlServices.TranslateCommandTree). I don't see the reasoning behind rendering constants as literals in select statements - maybe someone can enlighten me (we don't really care about migrations in this context).

This is a bit convoluted to explain.

There is a certain query pattern emitted by EF6 which is sent to the driver which contains constant expressions. This happens in the following situation:

1. You have entities using inheritance (I use table-per-type but I think the other inheritance patterns can expose this problem in slightly different forms).

2. You issue a LINQ query that has a ```Select``` clause that looks like this:
```
DbContext.Bases.Select(
    x => x is Child1 
    ? "Something"
    : x is Child2 
    ? "SomethingElse" : "Unknown");
```

In this case EF6 emits SQL that is similar to this:
```
   SELECT 
        -- ternary expression translated here:
       CASE WHEN Extent1.Computed = '0X0X0X' THEN 'Something'
       ELSE WHEN Extent1.Computed = '0X0X0Y' THEN 'SomethingElse'
       ELSE 'Unknown' END AS Projection1
   FROM (SELECT  
          CASE WHEN Child1.Id IS NOT NULL THEN '0X0X0X' 
          ELSE WHEN Child2.Id IS NOT NULL THEN '0X0X0Y' AS Computed
          --- and so on for each Child class mentioned in the ternary expression
          END
   FROM Bases
   LEFT JOIN Child1 ON Bases.Id = Child1.Id
   LEFT JOIN Child2 ON Bases.Id = Child2.Id) AS Extent1
```

Basically it attempts to compute a constant column that acts as a string type discriminator for each row, so that if the user re-uses the ternary expression somewhere or issues another one it doesn't need to repeat the join conditions (as far as I could tell).

I think to account for possible further subtypes, it even tries to compute a common discriminator prefix and it uses LIKE statements on it to allow for filtering a child that is also the parent for deeper sub-children.

Now, since the changes to support unknown types, ConstantExpression no longer adds ```::varchar``` after string literals when translating to SQL. Normally this works fine, except for the case when the query causes EF6 to wrap the entire query multiple times while containing such a computed expression.

Eventually it hits the situation where PostgreSQL cannot execute the LIKE or = comparison on the discriminator column and the query fails with ```Cannot convert 0X0X0X ....```.

Perhaps it doesn't send them as parameters because it is easier to implement this way, or perhaps to make caching the query execution plan possible for the database server. But even if it did send them as parameters it wouldn't change the nature of the problem because string parameters are also sent as without specifying their type and it would still hit the same problem.

> ... we can simply add ::varchar to string literal handling in ConstantExpression solving the 0X0X bug and maintaining support for unsupported types as string.

Initially my earlier pull request was along those lines. I made the driver emit ```::varchar``` for all string constants. That did solve the problem but that quickly made queries that used "unknown" types very cumbersome to write (and constitutes a big breaking change for those who depend on this feature already since 3.0), because now you had to write explicit casts in the query (and my pull request introduces an explicit casting function) that sent unknown type strings. 

This became apparent when all my full text search unit tests started failing and needed explicit casts and even the varbinary test started failing.

I tried to reduce the impact by making this behavior only for SELECTs and not for INSERT or UPDATE (or DELETE), but it was still too unwieldy and still a huge breaking change.

Queries that worked earlier for people would now fail unless they wrote in an explicit cast.

--

So I thought of an alternative solution, I debugged the translation of such a query (I have a unit test in this pull request that produces one) and found that I can restrict the fix to instances of DbConstantExpression that had string values in the code path that processes "projection" expressions emitted by EF6 only.

Thus the problem was solved without changing any existing behavior (all existing unit tests pass unchanged) and there is almost no breaking behavior change.

For the cases where a user writes a convoluted LINQ query that artificially introduces wrapping around an unknown value sent as string, I left the explicit cast function to be used in that case and there is a test for it.

Hope that helps to clarify things, let me know if there's a better way or something I've missed. I've been using this fix in my own fork of this project for a while in pretty convoluted inheritance queries and so far the bug hasn't resurfaced.

**Comment by roji** [comment]
@rwasef1830 thanks for the long and patient explanation.

Regardless of anything else, the explicit cast function looks like a great addition to me.

Everything you say makes sense, but I still don't understand something. If we add back `::varchar` to string literals, queries indeed start to break because unsupported types are no longer sent as unknown-typed strings. But, as I said above, the thing I don't understand is why any user data (e.g. text search, json, macaddr) gets sent as literals rather than as parameters. The current EF6 logic seems to be to send user data as literals for SELECT statements, and as parameters otherwise. This is what makes both user data *and* EF6 literals (like X0X0) end up in the same function.

So my question is this: if we switch to parameters everywhere for *user data* (leaving literals for EF6 X0X0 et al), by changing `NpgsqlServices.TranslateCommandTree`, would it not be safe to add back `::varchar` to literals (as it would now only be added to EF6 X0X0 et al).

I tried to do this and quickly ran into test failures. Before really diving into it I wanted to share these thoughts to see if I'm really missing something fundamental.

**Comment by roji** [comment]
Ah, it seems I had things a bit mixed up. It doesn't really seem possible to cleanly distinguish between user data and EF6-generated data. Will investigate a little bit more but your solution seems clear and probably correct to me.

**Comment by rwasef1830** [comment]
> It doesn't really seem possible to cleanly distinguish between user data and EF6-generated data.

@roji Exactly. That is what I concluded after debugging. So the goal is to change it in a minimal way that covers this EF6 edge case while not changing any behavior as much as possible.

**Comment by roji** [comment]
@rwasef1830 I think I understand. I'll investigate a bit more and will probably merge your PR very soon.

**Comment by rwasef1830** [comment]
@roji 
> But, as I said above, the thing I don't understand is why any user data (e.g. text search, json, macaddr) gets sent as literals rather than as parameters. The current EF6 logic seems to be to send user data as literals for SELECT statements

I'm also not sure, but most likely to facilitate query plan caching or query caching on the DB side. Things such as column type discriminator computation strategy should only change with the schema, so I think it shouldn't be expressed as a variable.

**Comment by roji** [comment]
@rwasef1830, I've merged this into dev. Would you like to submit another PR against hotfix/3.1.1 to have this released soon?

**Comment by rwasef1830** [comment]
@roji Will do shortly
