### ISSUE TITLE
Code First - Schema does not exist

### ISSUE THREAD

**Issue by roji** [npgsql/EntityFramework6.Npgsql#34]
_From @DemonHaunted on April 25, 2016 2:22_

FYI Error with npgsql v 3.0.5.0 when conducting a code first pattern.

Issue occurs when the schema name has upper case letters in it when used in 

`modelBuilder.HasDefaultSchema(<SchemaName>);` 

within the OnModelCreating method of the data model class.

Error returned is <SchemaName> does not exist.

Works fine when schema name is lower case however.

_Copied from original issue: npgsql/npgsql#1044_

**Comment by roji** [comment]
This is probably a dup (or related to) #691

**Comment by MurariAlex** [comment]
This was fixed by PR https://github.com/npgsql/EntityFramework6.Npgsql/pull/74
/cc @roji @rwasef1830 @piksel

**Comment by rwasef1830** [comment]
@MurariAlex Thanks for updating the issue.
