### ISSUE TITLE
Support UPSERT statement introduced in Postgres 9.5

### ISSUE THREAD

**Issue by beeleebow** [npgsql/EntityFramework6.Npgsql#54]
Hi guys, 

Postgres 9.5 introduced a [INSERT ... ON CONFLICT DO NOTHING/UPDATE ("UPSERT")](https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29) feature. It would be great if calling dbContext.SomeSet.AddOrUpdate(someEntity) actually ended up producing one of these SQL statements, instead of the current SELECT followed by either an UPDATE or INSERT.

Is this something that is possible?

Thanks for all your hard work.

**Comment by rwasef1830** [comment]
@beeleebow The problem is that EF6 implements this method very explicitly as an extension method that does a SELECT first, then decides to update or add. It does not defer to the provider to allow it to make such decision, so it is not actually possible to do this using that method.

**Comment by beeleebow** [comment]
Thanks for the answer @rwasef1830. Thats a shame. I'll close this issue.

Keep up the good work.
