### ISSUE TITLE
Naming convention for Joint Table for 2 models with ManyToMany relationship

### ISSUE THREAD

**Issue by shaojun** [npgsql/EntityFramework6.Npgsql#55]
hi,
I have 2 models (say PosTransaction and PosItem) with a Property in each to form a ManyToMany relationship, all works good and I can see the Joint table has been created with name: **PosTransactionModelPosItemModels**.   Until today I add another Foreign Key property(Point to another standardalone model which only have some plain properties, and PosTransaction works as the Many end) to PosTransaction model, then former works good code pop up an exception in here:
`var entityCollection = db.PosTransactionModels.Include(trx => trx.SaleItems)
                         .Where(trx => trx.Id == targetTrx.Id)
                         .SelectMany(t => t.SaleItems).ToList();`

Exception detail:
> [PostgresException (0x80004005): 42P01: relation "public.PosItemModelPosTransactionModels" does not exist]
   Npgsql.NpgsqlConnector.DoReadMessage(DataRowLoadingMode dataRowLoadingMode, Boolean isPrependedMessage) +318
   Npgsql.NpgsqlConnector.ReadMessageWithPrepended(DataRowLoadingMode dataRowLoadingMode) +195
   Npgsql.NpgsqlConnector.ReadExpecting() +39
   Npgsql.NpgsqlDataReader.NextResultInternal() +235
   Npgsql.NpgsqlDataReader.NextResult() +126

By set a break point to above code, and check the generated sql statement:

> {SELECT "Extent2"."Id", "Extent2"."ItemId", "Extent2"."SnapShotModelId", "Extent2"."ItemName", "Extent2"."ItemDepartmentId", "Extent2"."UnitId", "Extent2"."Price", "Extent2"."TaxItemGroupId", "Extent2"."DateToActivate", "Extent2"."DateToDeactivate", "Extent2"."ItemBarCode" FROM "public"."PosItemModelPosTransactionModels" AS "Extent1" INNER JOIN "public"."PosItemModels" AS "Extent2" ON "Extent1"."PosItemModel_Id" = "Extent2"."Id" WHERE "Extent1"."PosTransactionModel_Id" = $1}

Have no idea why it searching for **public.PosItemModelPosTransactionModels**, shouldn't it be the  **PosTransactionModelPosItemModels** ??  Even by rolled back several migration to very early state, still got this exception, any idea?

[edit0: adding 2 model definition]
```
public class PosTransactionModel
    {
        public int Id { get; set; }
        public ICollection<PosItemModel> SaleItems { get; set; }
        ...
        ...
    }

public class PosItemModel
    {
        public int Id { get; set; }
        public List<PosTransactionModel> SoldInPosTransactions { get; set; }
    }
```

**Comment by rwasef1830** [comment]
I've seen this happen with EF6. Sometimes when you change random things, EF suddenly decides to flip the junction table definition (when you do Add-Migration, you'll see it try to drop the old one and create the new flipped one).

The only solution is to to use the code config to specify the junction table explicitly. See here https://msdn.microsoft.com/en-us/data/hh134698.aspx 

It involves overriding OnModelCreating in your DbContext class and handling the many-to-many explicitly with the fluent API.

**Comment by shaojun** [comment]
@rwasef1830 so this is the issue in EF6, but not in EntityFramework6.Npgsql? So I have to re-create all the database to get this `OnModelCreating` called, correct?
If this confirmed, then it's a critical issue since all ManyToMany field would break?

**Comment by rwasef1830** [comment]
no. just add this method on your DbContext and it will use the existing junction table correctly.
It is a well known and documented issue.

**Comment by shaojun** [comment]
@rwasef1830 I just made that FluentAPI to explicitly create the ManyToMany relationship in `OnModelCreating`, and I dropped the old database, then use `Update-database` to regenerate the whole db, but looks like the Joint table is not with the name I specified, so the `OnModelCreating` is not get called, any idea why?
thx!

**Comment by shaojun** [comment]
@rwasef1830 I just made that fluent API in `OnModelCreating` to explicitly specify the ManyToMany relationship, but I noticed even I dropped the database and let's the EF re-create a new one, the `OnModelCreating` still got no called, I've tried deleted all migration history files, run `Update-database` again, this time the Joint table created with the name I specified, do you have any idea why?

**Comment by rwasef1830** [comment]
@shaojun OnModelCreating is a protected virtual method in DbContext. You need to define it in your DbContext-child class.

Example:
```
class MyDbContext : DbContext
{
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // This will create the junction table with left key PostId and right key UserId, otherwise
           // sometimes EF6 will suddenly decide to flip the table later.
            modelBuilder.Entity<User>()
                .HasMany(x => x.Posts)
                .WithMany(x => x.Users);
            modelBuilder.Entity<Post>();
        }
}
```

Maybe post some code from your DbContext class.

**Comment by shaojun** [comment]
@rwasef1830  just like i said, If I delete all code based migration files and re-run `Update-database`, my `onModelCreating` would works, otherwise, still the EF will use the default name to create the Joint table, this is my db context:
```
public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext()
            : base("PgDatabaseContext")
        {
        }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // PostgreSQL uses the public schema by default - not dbo.
            modelBuilder.HasDefaultSchema("public");

            modelBuilder.Entity<PosTransactionModel>()
                .HasMany(p => p.SaleItems)
                .WithMany(t => t.SoldInPosTransactions)
                .Map(mc =>
                {
                    mc.ToTable("PosTransactionModelPosItemModelsManualFixed");
                    mc.MapLeftKey("PosTransactionModelId");
                    mc.MapRightKey("PosItemModelId");
                });
}
```

thank you!
