### ISSUE TITLE
EF Data First: Unable to find the requested .net framework provider

### ISSUE THREAD

**Issue by vanceism7** [npgsql/EntityFramework6.Npgsql#69]
So I've been trying to troubleshoot this error for just a day or so now, and I've narrowed it down to the app.config. I installed the npgsql vsix extension from the visual studio market place. This allowed me to see the postgres provider in the server explorer, but it wouldn't show up in the EF Model generator update wizard. 

When I use nuget to install EntityFramework6.Npgsql, the app config that gets generated automatically then inserts that postgres provider option in the update wizard, but it must be incorrect because when I use it, it gives the message upon trying to connect: 
"Unable to find the requested .net framework provider, it may not be installed".

So Im assuming the bigger issue here is that the update wizard isn't respecting the vsix installation, but it may also be an issue that my app config gets a dbprovider entry when I install the entityframework6.npgsql package.  Or perhaps the app.config is supposed to reference the work done by the vsix. (I'm not really sure how the internals of vsix and providers and all that work here, so Im just making assumptions)

Heres the dbprovider entry that gets created in my app.config when I install the package. If I remove the npgsql line, then the provider disappears out of the list of providers. If I leave it in, then it shows in the list but says the provider isn't found when you try to use it
```xml
<providers>
    <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    <provider invariantName="Npgsql" type="Npgsql.NpgsqlServices, EntityFramework6.Npgsql" />
</providers>
```

Anyways, any assistance here just to get the data model to generate would be great. Thanks!

P.S: This is a fresh install of using npgsql, I never modified the GAC or anything like that. I started off with the vsix

**Comment by vanceism7** [comment]
Ok I figured out a little bit more about this. If I try to add the database connection from the server explorer, the data providers there do respect the vsix install and Im able to connect to the database. But from the ef data wizard, the vsix provider isn't visible. Also, something about installing the nuget packages will also cause the server explorer to have the same error as the ef data wizard unless I restart visual studio. 

If I add the database connection from server explorer, and then go into the ef data wizard, then my connection will show up in there and work. (Atleast the 2nd time I tried this, it did. The first time, it still didnt see the connection but now it is seeing it)

**Comment by vanceism7** [comment]
Nvm: as per issue 1439, I'm assuming that entity frameworks model wizard is probably using the ADO.NET DbProviderFactory API, which doesn't care about the vsix. This would explain why the server explorer can see the provider but not the ado.net model generator. You have to use the GAC modification with the app.config modified for the model generator to work correctly.

Here's issue 1439 for reference
https://github.com/npgsql/npgsql/issues/1439

**Comment by cosmoKrick42** [comment]
I've tried adding this code in app.config but i still facing same error.
<entityFramework>
		<defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework" />
		<providers>
			<provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
			<provider invariantName="Npgsql" type="Npgsql.NpgsqlServices, EntityFramework6.Npgsql" />
		</providers>
	</entityFramework>
	<system.data>
		<DbProviderFactories>
			<remove invariant="Npgsql"/>
			<add name="Npgsql Data Provider" invariant="Npgsql" description=".Net Data Provider for PostgreSQL" type="Npgsql.NpgsqlFactory, Npgsql, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7" support="FF"/>
		</DbProviderFactories>
	</system.data>
