### ISSUE TITLE
Avoid empty string in query when string.Empty is specified as default schema

### ISSUE THREAD

**Issue by fraps17** [npgsql/EntityFramework6.Npgsql#72]
We have generated context with following configuration in `OnModelCreating:`

`modelBuilder.HasDefaultSchema(String.Empty);`

When running queries, the context generates (please note the double quotes for the schema name)

`SELECT "Extent1"."<column1>", "Extent1"."<column2>",...
FROM ""."<table>" AS "Extent1" WHERE ...
`

while same context configuration on Oracle produces

`SELECT "Extent1"."<column1>", "Extent1"."<column2>",...
FROM "<table>" AS "Extent1" WHERE ...
`

Is it possible to avoid the schema in the query string when schema name is an empty string?

**Comment by Emill** [comment]
Doesn't seem so right now. Feel free to send in a pull request. The right location to change should be https://github.com/npgsql/EntityFramework6.Npgsql/blob/dev/src/EntityFramework6.Npgsql/SqlGenerators/SqlBaseGenerator.cs#L553.
