### ISSUE TITLE
EF6 Code First + Redshift + Npgsql: Cannot create table with identity columns.

### ISSUE THREAD

**Issue by slope-taylor** [npgsql/EntityFramework6.Npgsql#92]
After setting up an EF connection to a redshift cluster using Npgsql, I cannot create database tables that have an identity column inside a code-first migration.  Although identity columns are supported in Redshift, I get the following error: Column "results.id" has unsupported type "serial4".  Seems to be creating it as a serial4 instead of an int with the "identity" attribute.

I know that EF and Redshift don't play nicely during querying on identity columns, but I think it's possible to create the DB with EF.

My current workaround is to write the SQL for the table create manually in the migration.

Simple EF migration to reproduce this:
```
CreateTable(
                "dbo.Results",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(),
                    })
                .PrimaryKey(t => t.Id);
```

**Comment by roji** [comment]
As explained in https://github.com/npgsql/EntityFramework6.Npgsql/issues/96#issuecomment-386325819, Redshift's SQL dialect is sufficiently different from PostgreSQL that properly supporting it from EF6 is very non-trivial and isn't currently a goal.

You may indeed be able to get away with creating the tables manually and then having EF6 issue some queries, but you'll likely run into some incompatibility issues there as well (see E-quoted string incompatibility raised in #96).

In theory it's possible for someone to investigate what an EF6 SQL compatibility mode for Redshift would entail.
