### ISSUE TITLE
Migration scripts incorrect for Redshift

### ISSUE THREAD

**Issue by slope-taylor** [npgsql/EntityFramework6.Npgsql#96]
When using Amazon Redshift, the SQL generated for the migration history table uses the "E" character before the string literals, which is invalid.  It appears to need to be the "N" character.  I'm not sure if E is valid in other Postgresql databases, but it's throwing an exception in Redshift: "Npgsql.PostgresException (0x80004005): 42704: type "e" does not exist"

**Comment by roji** [comment]
@slope-taylor Redshift has several important SQL differences when compared to regular modern PostgreSQL, and SQL generated by Entity Framework simply won't run on Redshift. One notable example is the lack of SERIAL columns in Redshift, which has its own IDENTITY feature for that. The problems go beyond the E'' string literals.

So unfortunately, while you can use Npgsql (ADO.NET driver) to connect to Redshift and write your SQL, you can't use Entity Framework with it.

**Comment by slope-taylor** [comment]
@roji Thanks for the explanation.  You should probably close the other issue I created as well, then (#92) which is related to identity columns.

**Comment by roji** [comment]
Thanks, that issue slipped by me...
